#!/bin/bash

if [ -f /etc/devmode ];then
  export DEVMODE="open"
fi


echo "Mount base fs"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs  devtmpfs  /dev

#echo "activate external modules"
#cat /etc/mod.cfg | sh

echo "Execute origin script"
/lib/scripts/origin

# Fallback into shell
bash
