#!/bin/busybox sh

echo "Mount base fs"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs  devtmpfs  /dev

#echo "activate external modules"
#cat /etc/mod.cfg | sh

echo "Execute origin script"
/lib/scripts/origin

# Fallback into shell
sh
