#!/bin/bash


if [ -d "/lib/scripts/" ];then
  srcPATH="/lib/scripts"
else
  srcPATH="."
fi

# '.' is equivalent to the good old 'source' in bash
source $srcPATH/print_menue.sh
source $srcPATH/scan_boot.sh

get_scan # return $OPTIONS

OPTIONS_useNAME=""
for option in ${OPTIONS[@]}
do
  OPTIONS_useNAME="$(echo $option | cut -f4 -d"/")_on_/dev/$(echo $option | cut -f3 -d"/") $OPTIONS_useNAME"
done
selection "Selection:" "$OPTIONS_useNAME"
echo $SEL
